name: Lars
favicon: null
layout_spectrum: 0.9615996915381402
typography_spectrum: 0.5338285909965634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.921531384345144
  lightness: 0.2254397312644869
  saturation: 0.8168296460062265
  rhythmicContrast: 0.29483402078039944
purpose: []
